spring:
  application:
    name: spring-start
    #数据库连接信息配置
# jdbc 数据库的连接信息
  datasource:
    # 使用-来分割驼峰，注入的实体中使用驼峰命名来获取对应配置的字段值
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/byj_data
    username: root
    # 0开头必须加引号 ''
    password: Pass123!

  main:
    # 解决循环依赖问题
    allow-circular-references: true

  # controller 文件上传大小的限制
  servlet:
    multipart:
      #单个文件最大可上传的大小，默认时1MB
      max-file-size: 10MB
      #单次请求所有文件最大可上传的大小，默认时10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    #配置SQL日志打印在控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名规则映射 例子：abc_xyz --> abcXyz
    map-underscore-to-camel-case: true

#打开spring事务管理的debug日志
logging:
  level:
    org:
      springframework:
        jdbc:
          support:
            JdbcTransactionManager: debug


server:
  port: 8089

##自定义配置
aliyun:
  oss:
    endpoint: oss-rg-china-mainland.aliyuncs.com
    bucket: mypics

